config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :flats do
    resources :candidacies, only: [:index, :new, :show, :edit, :update] do
      resources :messages, only: [:index, :new, :create]
    end
    resources :availabilities
    resources :messages
    collection do
      get :extract_from_lbc
    end
  end
  resources :candidacies do
    resources :bookings
    resources :messages, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :profils, only: [:show, :edit, :update]
  resources :bookings, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidacy.rb
class Candidacy < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :user, uniqueness: { scope: :flat }
  # validate :user_is_not_owner

  # def user_is_not_owner
  #   if self.flat.user == self.user
  #       errors.add_to_base("Vous ne pouvez pas candidater pour votre appartement.")
  #   end
  # end
end

app/controllers/candidacies_controller.rb
class CandidaciesController < ApplicationController
  before_action :set_candidacy, only: [:show, :edit, :update, :destroy]
  before_action :set_flat, only: [:new, :create]

  def index
    if params[:flat_id].nil? #Côté locataire: Mes candidatures
      @candidacies = policy_scope(Candidacy).where(user: current_user).order(created_at: :desc)
      sort_candidacies(@candidacies)
      @sidebar_title = "Mes candidatures"
      @flats = []
      @candidacies.empty? ? @unread_mess_flat = 0 : count_unread_messages(@candidacies.first.flat)
      @candidacies.each do |candidacy|
        @flats << candidacy.flat
      end
      @flats_geo = @flats.select{ |flat| !flat.latitude.nil? && !flat.longitude.nil?}

      @markers = @flats_geo.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          infoWindow: { content: render_to_string(partial: "/shared/map_box", locals: { flat: flat }) }
        }
      end
    else #Côté propriétaire: Les candidatures par appartement
      set_flat
      count_unread_messages(@flat)
      @flats = policy_scope(Flat).where(user: @flat.user).order(created_at: :desc)
      @candidacies = policy_scope(Candidacy).where(flat_id: params[:flat_id]).order(created_at: :desc)
      sort_candidacies(@candidacies)
    end
  end

  def sort_candidacies(candidacies_tot)
    @candidacies_sorted = []
    @candidacies_sorted << candidacies_tot.where(status: "Dossier retenu").order(updated_at: :desc)
    @candidacies_sorted << candidacies_tot.where(status: "Visite effectuée").order(updated_at: :desc)
    @candidacies_sorted << candidacies_tot.where(status: "Visite programmée").order(updated_at: :desc)
    @candidacies_sorted << candidacies_tot.where(status: "En attente").order(updated_at: :desc)
    @candidacies_sorted << candidacies_tot.where(status: "Dossier archivé").order(updated_at: :desc)
  end

  def show
    if params[:flat_id].nil?
      @marker = [{
        lat: @candidacy.flat.latitude,
        lng: @candidacy.flat.longitude,
        infoWindow: { content: render_to_string(partial: "/shared/map_box", locals: { flat: @candidacy.flat }) }
      }]
      @messages = policy_scope(Message).where(candidacy: @candidacy).order(created_at: :desc)
    else
      @candidacies = policy_scope(Candidacy).where(flat_id: params[:flat_id]).order(created_at: :desc)
      @messages = policy_scope(Message).where(flat_id: params[:flat_id]).order(created_at: :desc)
    end
    @message = Message.new
    @flat = @candidacy.flat
    @sidebar_title = @flat.name
  end

  def new
   @candidacy = Candidacy.new
   authorize(@candidacy)
  end

  def create

    @candidacy = Candidacy.new(candidacy_params)

    authorize(@candidacy)

    @candidacy.flat = @flat
    @candidacy.user = current_user

    if @candidacy.save
      redirect_to @candidacy, notice: 'Candidacy was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @candidacy.update(status: params[:candidacy][:status])
    redirect_to flat_candidacies_path(@candidacy.flat)
  end

  def destroy
    @candidacy.destroy
    redirect_to candidacies_path, notice: 'Candidacy was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_flat
    @flat = Flat.find(params[:flat_id])
    authorize(@flat)
  end

  def set_candidacy
    @candidacy = Candidacy.find(params[:id])
    authorize(@candidacy)
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def candidacy_params
    params.permit(:flat_id, :user_id)
  end

  def count_unread_messages(flat)
    @unread_mess_flat = 0
    flat.candidacies.each do |candidacy|
      @unread_mess_flat += candidacy.messages.where(read: false).where(recipient: current_user).count
    end
    return @unread_mess_flat
  end
end

app/views/candidacies/_candidacy_class_name.html.erb
<% if candidacy_group.first.status == "Dossier retenu" %>
  <i class="fas fa-check-circle"></i> <%= candidacy_group.first.status%>
<% elsif candidacy_group.first.status == "Visite effectuée" %>
  <i class="far fa-calendar-check"> </i> <%= candidacy_group.first.status%>
<% elsif candidacy_group.first.status == "Visite programmée" %>
  <i class="far fa-calendar-alt folder-icon"></i> <%= candidacy_group.first.status%>
<% elsif candidacy_group.first.status == "En attente" %>
  <i class="far fa-clock"> </i> <%= candidacy_group.first.status%>
<% elsif candidacy_group.first.status == "Dossier archivé" %>
  <i class="fas fa-archive"> </i> <%= candidacy_group.first.status%>
<% end %>

app/views/candidacies/_card.html.erb
<%= link_to(candidacy_path(candidacy)) do %>
  <div class="candidacy_card_body">
    <span class="price"><%= candidacy.flat.price %>€</span>
  </div>
  <div class="candidacy_card_footer">
    <div class="candidacy_card_title"><%= candidacy.flat.name %></div>
    <%= cl_image_tag candidacy.flat.user.avatar, class: "candidacy_card_avatar"%>
  </div>
<% end %>

app/views/candidacies/_card_flat.html.erb
<%= link_to(candidacy_path(candidacy)) do %>
  <div class="card">
    <div class="candidacy_card_body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= candidacy.flat.photo[0] %>);">
      <div class="candidacy_card_title"><strong><%= candidacy.flat.name %></strong> <br> <%= candidacy.flat.address %> <br> <%= candidacy.flat.price %>€</div>
      <% if  candidacy.status == "Visite programmée" %>
        <div class="candidacy_booking_date">
          <i class="far fa-calendar-alt folder-icon"></i> <%= I18n.l(candidacy.bookings.first.availability.start_time, format: "%A %d %B %H:%M") %>
        </div>
      <% end%>
      <% if candidacy.status == "Dossier retenu"  %>
        <div class="icon-award-candidate">
          <i class="fas fa-bookmark bookmark-award"><i class="fas fa-certificate certificate-award"></i></i>
        </div>
      <% end %>
    </div>
    <div class="candidacy_card_footer">
      <div class="avatar-img">
        <%= cl_image_tag candidacy.flat.user.avatar, class: "avatar"%>
      </div>
      <div class="icon-message">
        <%= link_to candidacy_messages_path(candidacy) do %>
          <% if !candidacy.messages.empty? %>
            <% if (candidacy.messages.last.sender == candidacy.flat.user && !candidacy.messages.last.read) %>
              <i class="fas fa-comments mess-icon"><i class="fas fa-circle unread-message-dot"></i></i>
            <% else %>
              <i class="fas fa-comments mess-icon"></i>
            <% end %>
          <% else %>
            <i class="fas fa-comments mess-icon"></i>
          <% end %>
        <% end %>
      </div>
      <div class="icon-calendar">
        <%= link_to candidacy_bookings_path(candidacy) do %>
          <% if candidacy.status == "Visite effectuée" || candidacy.status == "Dossier retenu" %>
            <i class="far fa-calendar-check"></i>
          <% elsif candidacy.status == "Visite programmée" %>
            <i class="far fa-calendar-alt folder-icon"><i class="fas fa-check-circle folder-check"></i></i>
          <% else %>
            <i class="far fa-calendar-alt"></i>
          <% end%>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/candidacies/_card_tenant.html.erb
<div class="tenant-card">
  <div class="img-card-tenant">
    <%= cl_image_tag candidacy.user.avatar, class: "avatar-large"%>
  </div>
  <div class="tenant-name">
    <p><%= "#{candidacy.user.first_name} #{candidacy.user.last_name}" %></p>
  </div>
  <div class="tenant-message">
    <%= link_to flat_candidacy_messages_path(candidacy.flat,candidacy) do %>
      <% if !candidacy.messages.empty? %>
        <% if (candidacy.messages.last.sender == candidacy.user && !candidacy.messages.last.read) %>
          <i class="fas fa-comments mess-icon"><i class="fas fa-circle unread-message-dot"></i></i>
        <% else %>
          <i class="fas fa-comments mess-icon"></i>
        <% end %>
      <% else %>
        <i class="fas fa-comments mess-icon"></i>
      <% end %>
    <% end %>
  </div>
  <div class="tenant-folder">
    <%= link_to profil_path(candidacy.user) do %>
      <% if candidacy.user.profil_confirmed %>
        <i class="fas fa-folder folder-icon"><i class="fas fa-check-circle folder-check"></i></i>
      <% else %>
        <i class="fas fa-folder folder-icon"></i>
      <% end %>
    <% end %>
  </div>
  <div class="tenant-calendar">
    <%= link_to flat_availabilities_path(candidacy.flat) do %>
      <% if candidacy.status == "Visite programmée"  %>
        <i class="far fa-calendar-alt folder-icon"><i class="fas fa-check-circle folder-check"></i></i>
      <% elsif candidacy.status == "Visite effectuée" || candidacy.status == "Dossier retenu"%>
        <i class="far fa-calendar-check"></i>
      <% else %>
        <i class="far fa-calendar-alt"></i>
      <% end%>
    <% end %>
  </div>
  <div class="tenant-status text-center">
    <% if candidacy.status == "Dossier retenu" %>
      <p class="status accepted"><i class="fas fa-check-circle"></i></p>
    <% elsif candidacy.status == "Visite effectuée" %>
      <%= render 'candidacies/form', candidacy: candidacy, status: "Dossier retenu" %>
    <% elsif candidacy.status == "Visite programmée" %>
      <p class="status pending"> <%=  I18n.l(candidacy.bookings.first.availability.start_time, format: "%Hh %d/%m") %> </p>
    <% elsif candidacy.status == "En attente" %>
      <p class="status pending"><%= candidacy.status %></p>
    <% elsif candidacy.status == "Dossier archivé" %>
      <p class="status declined"> Archivé</p>
    <% end %>
  </div>
  <% if candidacy.status == "Visite effectuée" %>
    <div class="archive-candidacy">
      <%= render 'candidacies/form', candidacy: candidacy, status: "Dossier archivé"%>
    </div>
  <% end%>
</div>

app/views/candidacies/_form.html.erb
<%= simple_form_for(candidacy, method: :put) do |f| %>
  <%= f.hidden_field :status, value: status %>
  <% if status == "Dossier archivé" %>
    <%= f.button :button do %>
      <i class="fas fa-archive"> </i>
    <% end %>
  <% else %>
    <%= f.button :submit, 'Approuver', class: "btn btn-sm btn-primary accept-candidat" %>
  <% end %>
<% end %>

app/views/candidacies/_owner_dash_box_index.html.erb
  <div class="dashboard-tenant">
    <div class="row">
      <div class="col-xs-12">
        <!-- grille -->
        <% if @candidacies.empty? %>
          <h3>Tu n'as pas encore de candidature</h3>
        <% else %>
          <h3>Les dossiers de candidatures</h3>
          <div class="flex-container">
            <div class="candidacies">
              <div class="row">
                <div class="col-xs-12 candidacy_group_card_status">
                  <%= render 'schema_status'%>
                </div>
                <% @candidacies_sorted.each do |candidacy_group| %>
                  <% unless candidacy_group.empty? %>
                    <%= render 'candidacy_class_name', candidacy_group: candidacy_group %>
                    <div class="candidacy_group">
                      <% candidacy_group.each do |candidacy| %>
                        <div class="col-xs-12 candidacy_group_card">
                          <%= render 'card_tenant', candidacy: candidacy %>
                        </div>
                      <% end%>
                    </div>
                  <% end%>
                <% end%>
              </div>
            </div>
          </div>
        <% end%>
      </div>
    </div>
  </div>

app/views/candidacies/_schema_status.html.erb
<div class="schema-status-candidacy">
  <div class="schema-icon-status text-center">
    <i class="far fa-clock"> </i>
    <p>En attente</p>
  </div>
  <div class="straight-line">
    <p></p>
  </div>
  <div class="schema-icon-status text-center">
    <i class="far fa-calendar-alt folder-icon"></i>
    <p>Visite programmée</p>
  </div>
  <div class="straight-line">
    <p></p>
  </div>
  <div class="schema-icon-status text-center">
    <i class="far fa-calendar-check"> </i>
    <p>Visite effectuée</p>
  </div>
  <div class="straight-line">
    <p></p>
  </div>
  <div class="schema-icon-status text-center">
    <i class="fas fa-check-circle"></i>
    <p>Dossier retenu</p>
  </div>
</div>

app/views/candidacies/_tenant_dash_box_index.html.erb
<div class="col-xs-6">
  <!-- grille -->
  <div class="flex-container">
    <div class="candidacies">
      <div class="row">
        <% @candidacies_sorted.each do |candidacy_group| %>
          <% unless candidacy_group.empty? %>
            <%= render 'candidacy_class_name', candidacy_group: candidacy_group %>
            <div class="candidacy_group">
              <% candidacy_group.each do |candidacy| %>
                <div class="candidacy_card">
                  <%= render 'card_flat', candidacy: candidacy %>
                </div>
              <% end%>
            </div>
          <% end%>
        <% end%>
      </div>
    </div>
  </div>
</div>
<div class="col-xs-6">
  <div
    id="map"
    class="map_tenant_candidacies"
    data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/candidacies/edit.html.erb
<h1>Candidacies#edit</h1>

app/views/candidacies/index.html.erb
<% if params[:flat_id].nil? %>
<!-- Dashboard-box côté locataire -->
  <div class="dashboard">

    <div class="container">
      <div class="row flex">
        <div class="col-xs-3 sm-padding-right">
          <!-- sidebar-owner -->
          <%= render 'shared/sidebar_tenant' %>
        </div>

        <div class="col-xs-9 sm-padding-left">
          <!-- dashboard-box -->
          <div class="dashboard-box dash_tenant_candidacies">
            <%= render 'candidacies/tenant_dash_box_index'%>
          </div>
        </div>
      </div>
    </div>

  </div>
<% else %>
<!-- Dashboard-box côté proprio-->
  <div class="dashboard">

    <div class="container">
      <div class="row flex">
        <div class="col-xs-1 no-padding-right">
          <!-- tabs apparts -->
          <%= render 'shared/tabs_flats' %>
        </div>
        <div class="col-xs-3 sm-padding-right no-padding-left">
          <!-- sidebar-owner -->
          <%= render 'shared/sidebar_owner' %>
        </div>

        <div class="col-xs-8 sm-padding-left">
          <!-- dashboard-box -->
        <%= render 'candidacies/owner_dash_box_index'%>
        </div>
      </div>
    </div>

  </div>
<% end %>

app/views/candidacies/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="registration">
        <div class="card-form">
          <h3><%= @flat.name %> - <%= @flat.price %> € / mois</h3>
          <%= simple_form_for(@candidacy) do |f| %>
            <%= f.error_notification %>
            <br>
            <p><strong>Bienvenue sur myAgency !</strong></p>
            <br>
            <p>Ici, pas de frais d'agence, tout se fait très simplement et en direct avec le proprio (questions, programmation des visites...).</p>
            <br>
            <div class="form-inputs">
              <input id="flat_id" name="flat_id" type="hidden" value= <%= "#{params[:flat_id]}" %>>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Rejoindre l'espace de candidature", class: "btn btn-primary pull-center" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/candidacies/show.html.erb
<!-- Dashboard-box côté locataire -->
<div class="dashboard">

  <div class="container">
    <div class="row flex">
      <div class="col-xs-3 sm-padding-right">
        <!-- sidebar-owner -->
        <%= render 'shared/sidebar_tenant' %>
      </div>

      <div class="col-xs-9 sm-padding-left">
        <!-- dashboard-box -->
        <div class="dashboard-box">
          <%= render 'shared/tabs_candidacies' %>
          <%= render 'shared/dashboard_box' %>
        </div>
      </div>
    </div>
  </div>
</div>