config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :flats do
    resources :candidacies, only: [:index, :new, :show, :edit, :update] do
      resources :messages, only: [:index, :new, :create]
    end
    resources :availabilities
    resources :messages
    collection do
      get :extract_from_lbc
    end
  end
  resources :candidacies do
    resources :bookings
    resources :messages, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :profils, only: [:show, :edit, :update]
  resources :bookings, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_calendar_availabilities.html.erb
<!-- calendar structure côté proprio by Antoine -->
<div class="row calendar calendar-owner">
  <div class="col-xs-12 text-center">

    <div class="row">

        <div class="col-xs-12 availabilities-desktop">
          <div class="row">
            <div class="col-xs-1 availabilities-pagination">
              <a href="#" id="left-pagination"><i class="fas fa-chevron-left"></i></a>
            </div>
            <% 14.times do |i| %>
              <% day = @today + i %>
              <div class="col-xs-2 availabilities-day" <%= raw "style=\"display: none\""%> data-day-step="<%= i %>">
                <%= %>
                <div class="availabilities-day-title">
                  <div class="availabilities-day-name">
                    <%= I18n.l(day, format: '%A') %>
                  </div>
                  <div class="availabilities-day-date">
                    <%= day.day %> <%= I18n.l(day, format: '%B') %>
                  </div>
                </div>

                <div class="availabilities-slots" data-bookings="<%= @availabilities.to_json %>" data-flat="<%= @flat.id %>">
                  <% 12.times do |i| %>
                    <% date_hour = day.to_datetime + ((8 + i) * 3600).seconds %>
                    <% is_available = @availabilities.map(&:start_time).include?(date_hour) %>
                    <% availability_id = @availabilities.select{|av| av.start_time == date_hour}.map(&:id).first %>
                    <%= link_to flat_availabilities_path(@flat, date: date_hour), class:"availability-proprio" do %>
                      <div class="availabilities-slot <%= "availability" if is_available %>" data-dt="<%= date_hour %>" data-availability-id="<%= availability_id %>">
                        <%= date_hour.strftime('%Hh')  %>
                      </div>
                    <% end %>

                  <% end %>
                </div>
              </div>
            <% end %>

            <div class="col-xs-1 availabilities-pagination">
              <a href="#" id="right-pagination"><i class="fas fa-chevron-right"></i></a>
            </div>
          </div>
        </div>
    </div>

  </div>
</div>

app/views/shared/_calendar_booking.html.erb
<!-- calendar structure côté locataire by Antoine -->
<% if @candidacy.status == "Visite effectuée" || @candidacy.status == "Dossier retenu" %>
<h4> Visite effectuée</h4>
<p> <%= I18n.l(@bookings.first.availability.start_time, format: "%A %d %B %H:%M") %></p>

<% else %>
<!-- calendar structure côté locataire by Antoine -->
<div class="row calendar calendar-tenant">
  <div class="col-xs-12 text-center">

    <div class="row">

        <div class="col-xs-12 availabilities-desktop">
          <div class="row">
            <div class="col-xs-1 availabilities-pagination">
              <a href="#" id="left-pagination"><i class="fas fa-chevron-left"></i></a>
            </div>
            <% 14.times do |i| %>
              <% day = @today + i %>
              <div class="col-xs-2 availabilities-day" <%= raw "style=\"display: none\""%> data-day-step="<%= i %>">
                <%= %>
                <div class="availabilities-day-title">
                  <div class="availabilities-day-name">
                    <%= I18n.l(day, format: '%A') %>
                  </div>
                  <div class="availabilities-day-date">
                    <%= day.day %> <%= I18n.l(day, format: '%B') %>
                  </div>
                </div>
                <div class="availabilities-slots" data-bookings="<%= @bookings.to_json %>" data-candidacy-id="<%= @candidacy.id %>">
                  <% 12.times do |i| %>
                    <% date_hour = day.to_datetime + ((8 + i) * 3600).seconds %>
                    <% is_available = @availabilities.map(&:start_time).include?(date_hour) %>

                    <% availability_id = @availabilities.select{|av| av.start_time == date_hour}.map(&:id).first %>

                    <!-- ajouter insersion class 'booked' si is_booked == true -->

                    <!-- ajouter data-booking-id si is_booked == true -->
                    <% is_booked = @bookings.map(&:candidacy_id).include?(@candidacy) %>

                    <!-- booking_id = @bookings.select{|booking| booking.availability_id == @availability} -->
                    <%= link_to flat_availabilities_path(@flat, date: date_hour), class:"availability-tenant" do %>
                      <div class="availabilities-slot <%= "availability" if is_available %>" data-dt="<%= date_hour %>" data-availability-id="<%= availability_id %>">
                        <%= date_hour.strftime('%Hh')  %>
                      </div>
                    <% end %>

                  <% end %>
                </div>
              </div>
            <% end %>

            <div class="col-xs-1 availabilities-pagination">
              <a href="#" id="right-pagination"><i class="fas fa-chevron-right"></i></a>
            </div>
          </div>
        </div>
    </div>

  </div>
</div>

<% end %>

app/views/shared/_dashboard_box.html.erb
<!-- Dashboard-box de la vue show -->
<div class="row">
  <div class="col-xs-12">
    <div class="dashboard-box-head">
      <div>
        <%= link_to @flat.ad_url  do %>
          <i class="fas fa-link"></i>  <%= "Voir l'annonce" %>
        <% end %>
      </div>
        <div>
          <% if current_user.id == @flat.user_id %>
            <%= link_to edit_flat_path  do %>
              <i class="fas fa-pen-square"></i>
            <% end %>
          <% else %>
            <% owner_avatar = true %>
          <% end %>
      </div>
    </div>

    <div class="visuel">
      <div class="photo_flat">
        <% if owner_avatar %>
          <%= cl_image_tag @flat.user.avatar, class: "avatar-large-bordered"%>
        <% end %>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <% (@flat.photo.count - 1).times do |i| %>
            <li data-target="#myCarousel" data-slide-to="<%= i + 1 %>"></li>
            <% end %>
          </ol>

        <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active pic-flat">
              <%= cl_image_tag @flat.photo[0], crop: :fill %>
            </div>
            <% (@flat.photo.count - 1).times do |i| %>
              <li data-target="#myCarousel" data-slide-to="<%= i + 1 %>"></li>
            <% end %>
            <% if @flat.photo[1] %>
              <div class="item pic-flat">
                <%= cl_image_tag @flat.photo[1], crop: :fill %>
              </div>
            <% end %>
            <% if @flat.photo[2] %>
              <div class="item pic-flat">
                <%= cl_image_tag @flat.photo[2], crop: :fill %>
              </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div
        id="map"
        data-markers="<%= @marker.to_json %>">
      </div>

    </div>
    <div class="info_flat">
      <div class="metric_flat">
        <div><p><%= @flat.price %> € / mois</p></div>
        <div><p><i class="fas fa-expand-arrows-alt"></i> <%= @flat.surface %> m<sup>2</sup> </p></div>
        <div><p><i class="fas fa-bed"></i> <%= @flat.nb_rooms %> pièce(s)</p></div>
      </div>
      <div>
        <p><%= @flat.address %></p>

      </div>
    </div>

    <p><%= @flat.description.html_safe %></p>


    <h6 id="update_flat_date">Dernière mise à jour le
      <%= @flat.updated_at.day %>/<%= @flat.updated_at.month %>/<%= @flat.updated_at.year %>



    </h6>



  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Réalisé avec <i class="fa fa-heart"></i> @ Le Wagon Lyon
  </div>
</div>

app/views/shared/_map_box.html.erb
<p><%= flat.name %></p>
<p><%= flat.address %></p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-my.svg", height: 50 %> myAgency
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <% if current_user.candidacies.count > 0  %>
        <%= link_to candidacies_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
          <i class="fas fa-folder-open"></i>  <%= "Mes candidatures" %>
        <% end %>
      <% end %>

      <% if current_user.flats.count > 0  %>
        <%= link_to flats_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
          <i class="fas fa-home"></i>  <%= "Mes logements" %>
        <% end %>
      <% end %>

      <%= link_to new_flat_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
        <i class="fas fa-plus-circle"></i>  <%= "Ajouter une annonce" %>
      <% end %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profil_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Configuration") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
        <i class="fas fa-sign-in-alt"></i>  <%= t(".sign_in", default: "Connexion") %>
      <% end %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
      <div class="dropdown">
          <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if current_user.candidacies.count > 0  %>
              <li>
                <%= link_to candidacies_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
                  <i class="fas fa-folder-open"></i>  <%= "Mes candidatures" %>
                <% end %>
              </li>
            <% end %>
            <% if current_user.flats.count > 0  %>
              <li>
                <%= link_to flats_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
                  <i class="fas fa-home"></i>  <%= "Mes logements" %>
                <% end %>
              </li>
            <% end %>
            <li>
              <%= link_to new_flat_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
                <i class="fas fa-plus-circle"></i>  <%= "Ajouter une annonce" %>
              <% end %>
            </li>
            <li>
              <%= link_to profil_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Configuration") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
    <% else %>
      <%= link_to new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"  do %>
        <i class="fas fa-sign-in-alt"></i>  <%= t(".sign_in", default: "Connexion") %>
      <% end %>
    <% end %>


  </div>
</div>

app/views/shared/_sidebar_owner.html.erb
<!-- Sidebar du proprio -->
<div class="sidebar sidebar-owner">
  <!-- Ajouter un if @flat exist : Name Sinon "Nouveau" -->
  <h3><%= @flat.name ? @flat.name : "Nouveau logement" %></h3>
  <!-- <h3><%= @flat.name %></h3> -->
  <% if !@flat.id.nil? %>
    <ul>

      <li>
        <%= link_to_with_actif flat_candidacies_path(@flat) do %>
          <i class="fas fa-folder"></i>
            Dossiers
        <% end %>
      </li>
      <li>
        <%= link_to_with_actif flat_messages_path(@flat) do %>
          <i class="fas fa-envelope"></i>
          <% if @unread_mess_flat > 0%>
            Messages <%= "(#{@unread_mess_flat})" %>
          <% else%>
            Messages
          <% end %>
        <% end %>
      </li>

      <li>
        <%= link_to_with_actif flat_availabilities_path(@flat) do %>
          <i class="far fa-calendar-alt"></i>
            Visites
        <% end %>
      </li>

      <li>
        <%= link_to_with_actif flat_path(@flat) do %>
          <i class="fas fa-map-marker-alt"></i>
            Mon logement
        <% end %>
      </li>

    </ul>

    <!-- Button trigger modal -->
    <div class="share-link-flat text-center">
      <button type="button" class="btn btn-primary tooltips partager-btn" data-toggle="modal" data-target="#myModal">
        <!-- <span>Inviter de nouveaux locataires</span> -->
        <i class="fas fa-share-alt"></i>Partager
      </button>
    </div>

    <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
              <h3 class="modal-title" id="myModalLabel">Partage ce lien à tes potentiels locataires</h3>
            </div>
            <div class="modal-body">
              <input type="text" id="link-flat-share" value=<%= "http://www.myagency.top/flats/#{@flat.id}/candidacies/new"%>>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
              <button type="button" class="btn btn-primary">Copier le lien</button>
            </div>
          </div>
        </div>
      </div>
  <% end%>
</div>

app/views/shared/_sidebar_tenant.html.erb
<div class="sidebar sidebar-tenant">
  <h3><%= @sidebar_title %></h3>
    <ul>

      <li>
        <%= link_to_with_actif candidacies_path do %>
          <i class="fas fa-map-marker-alt"></i>
            Annonces
        <% end %>
      </li>

      <li>
        <%= link_to_with_actif bookings_path do %>
          <i class="far fa-calendar-alt"></i>
            Visites
        <% end %>
      </li>

    <ul>
</div>

app/views/shared/_tabs_candidacies.html.erb
<div class="tabs-candidacies">
  <div class="row">
    <div class="col-xs-4 text-center">
      <%= link_to_with_actif candidacy_path(@candidacy) do %>
        <div class="tab-candidacy">
          <i class="fas fa-home"></i>
          Le logement
        </div>
      <% end %>
    </div>
    <div class="col-xs-4 text-center">
      <%= link_to_with_actif candidacy_messages_path(@candidacy) do %>
        <div class="tab-candidacy">
          <% if !@candidacy.messages.empty? %>
            <% if (@candidacy.messages.last.sender == @candidacy.flat.user && !@candidacy.messages.last.read) %>
              <i class="fas fa-comments mess-icon"><i class="fas fa-circle unread-message-dot"></i></i>
              Messages
            <% else %>
              <i class="fas fa-comments mess-icon"></i>
              Messages
            <% end %>
          <% else %>
            <i class="fas fa-comments mess-icon"></i>
            Messages
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="col-xs-4 text-center">
      <%= link_to_with_actif candidacy_bookings_path(@candidacy) do %>
        <div class="tab-candidacy">
          <% if @candidacy.status == "Visite effectuée" || @candidacy.status == "Dossier retenu" %>
            <i class="far fa-calendar-check"></i>
          <% elsif @candidacy.status == "Visite programmée" %>
            <i class="far fa-calendar-alt folder-icon"><i class="fas fa-check-circle folder-check"></i></i>
          <% else %>
            <i class="far fa-calendar-alt"></i>
          <% end%>
          Planifier une visite
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_tabs_flats.html.erb
<div class="tabs-flats">
    <% @flats.each_with_index do |flat, i| %>
      <%= link_to flat_candidacies_path(flat), class:"tooltips" do %>
        <span><%= flat.name %></span>
        <div class="tab-flat <%= 'active' if @flat == flat %> <%= 'first-tab' if i == 0 %>" title= "<%= flat.name %>">
          <i class="fas fa-home"></i>
          <div class="flat-num">
            <%= i + 1 %>
          </div>
        </div>
      <% end %>
    <% end %>

    <%= link_to new_flat_path, class:"tooltips" do %>
      <span>Ajouter une annonce</span>
      <div class="tab-flat <%= 'active' if @flat.name == nil  %>">
        <i class="fas fa-plus-circle"></i>
      </div>
    <% end %>
</div>