config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :flats do
    resources :candidacies, only: [:index, :new, :show, :edit, :update] do
      resources :messages, only: [:index, :new, :create]
    end
    resources :availabilities
    resources :messages
    collection do
      get :extract_from_lbc
    end
  end
  resources :candidacies do
    resources :bookings
    resources :messages, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :profils, only: [:show, :edit, :update]
  resources :bookings, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  before_action :set_profil, only: [:show, :edit, :update]

  def edit
  end

  def update
    if @profil.update(profil_params)
      confirm_profil
      redirect_to profil_path(current_user), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_profil
    @profil = User.find(params[:id])
    authorize(@profil)
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def profil_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :id_card, :profil_confirmed, :tax_notice, :payslip, :avatar, :address)
  end

  def confirm_profil
    if (!profil_params[:id_card].nil? || @profil.id_card?) && (!profil_params[:tax_notice].nil? || @profil.tax_notice?) && (!profil_params[:payslip].nil? || @profil.payslip?)
      @profil.update(profil_confirmed: true)
    else
      @profil.update(profil_confirmed: false)
    end
  end
end

app/views/profils/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="card-form registration">
        <h3>Editer mon profile</h3>
        <%= simple_form_for @profil, url: profil_path do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :first_name, label: "Prénom"%>
            <%= f.input :last_name, label: "Nom" %>
            <%= f.input :address, label: "Adresse" %>
            <%= f.input :phone_number, label: "Un numéro de téléphone" %>
            <%= f.input :avatar, label: "Une petite photo de profil, c'est toujours sympa !" %>
            <%= f.input :avatar_cache, as: :hidden %>
            <div>
              <br>
              <h3>Pour ton dossier locataire (si tu veux être candidat à une location) :</h3>
            </div>
            <%= f.input :id_card, label: "Copie d'une pièce d'identité" %>
            <%= f.input :id_card_cache, as: :hidden %>
            <%= f.input :tax_notice, label: "Avis d'imposition" %>
            <%= f.input :tax_notice_cache, as: :hidden %>
            <%= f.input :payslip, label: "3 dernières fiches de salaire" %>
            <%= f.input :payslip_cache, as: :hidden %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, 'Mettre à jour mon profile', class: "btn btn-primary" %>
            <%= link_to 'Annuler', :back, class: "btn btn-default"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profils/edit.html.erb
<%= render 'form', profil: @profil %>

app/views/profils/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="card-form registration">
        <div class="profil_show">
          <% if @profil.profil_confirmed %>
            <h3> <%= "#{@profil.first_name} #{@profil.last_name}" %> <i class="fas fa-check-circle"></i></h3>
          <% else %>
            <h3> <%= "#{@profil.first_name} #{@profil.last_name}" %></h3>
            <p>Attention : merci de bien compléter ton profil pour candidater à une offre</p>
          <% end %>
         <div class="contact_head">
            <div class="contact_head_left">
              <%= cl_image_tag @profil.avatar, class: "avatar-large" %>
            </div>
            <div class="contact_head_right"></div>
              <ul>
                <li><%= "Adresse: #{@profil.address}" %></li>
                <li><%= "Tel: #{@profil.phone_number}" %></li>
              </ul>
            </div>
          </div>
          <div>
            <ul class="list_doc">
              <% if @profil.id_card? %>
                <li><i class="far fa-file-alt folder-icon"><i class="fas fa-check-circle folder-check"></i></i> <a href=<%= @profil.id_card %>> Carte d'identité </a> </li>
              <% else %>
                <li><i class="far fa-file-alt folder-icon"><i class="fas fa-times-circle folder-times"></i></i> Carte d'identité </li>
              <% end %>
              <% if @profil.tax_notice? %>
                <li><i class="far fa-file-alt folder-icon"><i class="fas fa-check-circle folder-check"></i></i> <a href=<%= @profil.tax_notice %>> Avis d'imposition </a> </li>
              <% else %>
                <li><i class="far fa-file-alt folder-icon"><i class="fas fa-times-circle folder-times"></i></i> Avis d'imposition </li>
              <% end %>
              <% if @profil.payslip? %>
                <li><i class="far fa-file-alt folder-icon"><i class="fas fa-check-circle folder-check"></i></i> <a href=<%= @profil.payslip %>> Fiche de salaire </a> </li>
              <% else %>
                <li><i class="far fa-file-alt folder-icon"><i class="fas fa-times-circle folder-times"></i></i> Fiche de salaire </li>
              <% end %>
            </ul>
          </div>
          <div>
            <% if @profil == current_user%>
              <%= link_to edit_profil_path(current_user) do %>
                <i class="fas fa-edit"></i>
                Editer mon profil
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>